-- ContaPro: MIGRACIÓN NO DESTRUCTIVA
-- NO hace DROP, TRUNCATE ni borra la tabla public.orders existente.
-- Ejecutar en Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.contapro_companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tax_id text,
  status text not null default 'Activo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('superadmin','admin','user')),
  company_id uuid references public.contapro_companies(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_clients (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.contapro_companies(id) on delete cascade,
  name text not null,
  document text,
  balance numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_suppliers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.contapro_companies(id) on delete cascade,
  name text not null,
  document text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_sales (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.contapro_companies(id) on delete cascade,
  document_no text not null,
  client_name text,
  amount numeric(14,2) not null default 0,
  date date not null default current_date,
  status text not null default 'Registrada',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_purchases (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.contapro_companies(id) on delete cascade,
  document_no text not null,
  supplier_name text,
  amount numeric(14,2) not null default 0,
  date date not null default current_date,
  status text not null default 'Registrada',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contapro_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  detail jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_contapro_clients_company on public.contapro_clients(company_id);
create index if not exists idx_contapro_suppliers_company on public.contapro_suppliers(company_id);
create index if not exists idx_contapro_sales_company_date on public.contapro_sales(company_id,date);
create index if not exists idx_contapro_purchases_company_date on public.contapro_purchases(company_id,date);
create index if not exists idx_contapro_profiles_company on public.contapro_profiles(company_id);

alter table public.contapro_companies enable row level security;
alter table public.contapro_profiles enable row level security;
alter table public.contapro_clients enable row level security;
alter table public.contapro_suppliers enable row level security;
alter table public.contapro_sales enable row level security;
alter table public.contapro_purchases enable row level security;
alter table public.contapro_audit_log enable row level security;

-- Funciones de autorización. No modifican ni eliminan datos de negocio.
create or replace function public.contapro_is_superadmin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.contapro_profiles p where p.id=auth.uid() and p.role='superadmin'); $$;

create or replace function public.contapro_my_company()
returns uuid language sql stable security definer set search_path=public
as $$ select company_id from public.contapro_profiles where id=auth.uid(); $$;

-- Policies: se eliminan SOLO policies con estos nombres para poder re-ejecutar
-- la migración; las tablas y sus datos NO se eliminan.
drop policy if exists contapro_companies_select on public.contapro_companies;
drop policy if exists contapro_companies_write on public.contapro_companies;
create policy contapro_companies_select on public.contapro_companies for select to authenticated
using (public.contapro_is_superadmin() or id=public.contapro_my_company());
create policy contapro_companies_write on public.contapro_companies for all to authenticated
using (public.contapro_is_superadmin()) with check (public.contapro_is_superadmin());

drop policy if exists contapro_profiles_select on public.contapro_profiles;
drop policy if exists contapro_profiles_write on public.contapro_profiles;
create policy contapro_profiles_select on public.contapro_profiles for select to authenticated
using (id=auth.uid() or public.contapro_is_superadmin());
create policy contapro_profiles_write on public.contapro_profiles for all to authenticated
using (public.contapro_is_superadmin()) with check (public.contapro_is_superadmin());

drop policy if exists contapro_clients_access on public.contapro_clients;
create policy contapro_clients_access on public.contapro_clients for all to authenticated
using (public.contapro_is_superadmin() or company_id=public.contapro_my_company())
with check (public.contapro_is_superadmin() or company_id=public.contapro_my_company());

drop policy if exists contapro_suppliers_access on public.contapro_suppliers;
create policy contapro_suppliers_access on public.contapro_suppliers for all to authenticated
using (public.contapro_is_superadmin() or company_id=public.contapro_my_company())
with check (public.contapro_is_superadmin() or company_id=public.contapro_my_company());

drop policy if exists contapro_sales_access on public.contapro_sales;
create policy contapro_sales_access on public.contapro_sales for all to authenticated
using (public.contapro_is_superadmin() or company_id=public.contapro_my_company())
with check (public.contapro_is_superadmin() or company_id=public.contapro_my_company());

drop policy if exists contapro_purchases_access on public.contapro_purchases;
create policy contapro_purchases_access on public.contapro_purchases for all to authenticated
using (public.contapro_is_superadmin() or company_id=public.contapro_my_company())
with check (public.contapro_is_superadmin() or company_id=public.contapro_my_company());

drop policy if exists contapro_audit_select on public.contapro_audit_log;
create policy contapro_audit_select on public.contapro_audit_log for select to authenticated
using (public.contapro_is_superadmin() or user_id=auth.uid());

-- Para crear el primer SuperAdmin:
-- 1) crea tu usuario desde Supabase Authentication;
-- 2) reemplaza TU_UUID por el UUID del usuario y ejecuta:
-- update public.contapro_profiles set role='superadmin' where id='TU_UUID';
--
-- El perfil puede crearse con:
-- insert into public.contapro_profiles(id,full_name,role)
-- values ('TU_UUID','Administrador principal','superadmin')
-- on conflict(id) do update set role='superadmin';

-- La tabla public.orders del sistema anterior NO se toca.
